### ISSUE TITLE
Handle null 

### ISSUE THREAD

**Issue by jonoabroad** [melrief/PureCSV#13]
Optional fields, Option[A] should either give a string representation of A or an empty string, not "".

**Comment by melrief** [comment]
For optional fields, the representation is the representation of A in case of `Some` or the empty string in case of `None`:

``` scala
scala> import purecsv.safe.converter.StringConverter
import purecsv.safe.converter.StringConverter

scala> val conv = StringConverter[Option[Int]]
conv: purecsv.safe.converter.StringConverter[Option[Int]] = purecsv.safe.converter.defaults.string.package$$anon$2@17232a4e

scala> conv.to(None)
res5: String = ""

scala> conv.to(Some(1))
res6: String = 1

scala> conv.from("")
res7: Option[Int] = None

scala> conv.from("1")
res8: Option[Int] = Some(1)
```

The fields is still there because csv "standard" allows to have empty fields to accommodate the fact that csv is tabular. For instance:

``` scala
scala> import purecsv.safe._
import purecsv.safe._

scala> case class Foo(opt: Option[Int], d: Double)

scala> Foo(None, 1.1d).toCSV(",")
res20: String = ,1.1
```

is the correct behaviour.

If you have optional field in the sense that you don't want them to be in the output, comma included, you can't do it right now because PureCSV doesn't support yet [sealed families of case classes](https://github.com/milessabin/shapeless/wiki/Feature-overview:-shapeless-2.0.0#generic-representation-of-sealed-families-of-case-classes). In future it should be possible to do

``` scala
scala> import purecsv.safe._
import purecsv.safe._

scala>:paste
sealed trait BaseTrait
case class Foo(i: Int, d: Double) extends BaseTrait
case class Bar(d: Double) extends BaseTrait

scala> Seq(Foo(1, 2.0d), Bar(3.0d)).toCSVLines(",")
1,2.0
3.0

scala> CSVReader[BaseTrait].readCSVFromString("1,2.0d\n3.0d")
Foo(1, 2.0)
Bar(3.0)
```

**Comment by jonoabroad** [comment]
:+1:  Thank you!
