### ISSUE TITLE
RecordSplitter.default* not configurable

### ISSUE THREAD

**Issue by suls** [melrief/PureCSV#5]
Hi Mario,

Turns out that some CSV files are actually TSV files (no pun intended).
To make this work, I had to do some boiler-plating/heavy-lifting ..

``` scala
object TSVReader {
  def apply[A](implicit rfcImp: RawFieldsConverter[A]): CSVReader[A] = new CSVReader[A] {
    override def rfc = rfcImp

    override def readCSVFromReader(r: Reader, skipHeader: Boolean = false): Iterator[Try[A]] = {
      val headerOffset = if (skipHeader) 1 else 0
      val records =
        OpenCSVSplitter.getRecords(
          r,
          '\t',
          RecordSplitter.defaultQuoteChar,
          headerOffset
        )
      records.map(rfc.tryFrom)
    }
  }
}

val records = TSVReader[Event].readCSVFromString("1\tfoo\n2\tbar")
```

Do you see this as something that should be configurable as well? If so, would you welcome a PR?

-- suls

**Comment by melrief** [comment]
I think the record separator should be configurable anyway and I welcome PRs that can make the library more flexible. IMHO all functions should have a parameter sep for record separator.

p.s. the name csv is not perfect, I know, because the library should be able to do more than read comma-separated values. Even so, the library started as CSV library and from there I took the name. No pun taken anyway, thanks for remarking it :).

**Comment by melrief** [comment]
@suls thanks to @jonoabroad PR, PureCSV 0.0.6 supports custom delimiters! Thank you both, closing this.
